import React from 'react';
import Head from 'next/head';

import Header from '../components/Header';

import { Background } from '../styles/pages/Home';

export default function Home() {
  return (
    <>
      <Head>
        <title>Telecine</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Background />
      <Header />
    </>
  );
}
